// ── News ──────────────────────────────────────────────────────────────────────
// Reads news.json generated by GitHub Actions (fetch_news.py + Gemini API).

function timeAgo(isoString) {
  const diff = Date.now() - new Date(isoString).getTime();
  const m = Math.floor(diff / 60000);
  if (m < 1)  return 'just now';
  if (m < 60) return `${m}m ago`;
  const h = Math.floor(m / 60);
  if (h < 24) return `${h}h ago`;
  return `${Math.floor(h / 24)}d ago`;
}

function renderNews(data) {
  const list = document.getElementById('news-nikkei');
  const meta = document.getElementById('news-meta');

  if (!data.articles || !data.articles.length) {
    list.innerHTML = '<p class="news-error">No articles.</p>';
    return;
  }

  list.innerHTML = data.articles.map(a => `
    <a class="news-card" href="${a.url}" target="_blank" rel="noopener noreferrer">
      <span class="news-source">Nikkei</span>
      <span class="news-title">${a.summary}</span>
      <span class="news-detail">${a.title}</span>
      <span class="news-time">${a.pub ? timeAgo(a.pub) : ''}</span>
    </a>
  `).join('');

  if (data.industries) {
    meta.innerHTML =
      `<span class="news-industries">Topics: ${data.industries.join(' · ')}</span>` +
      (data.fetchedAt ? ` · Updated ${timeAgo(data.fetchedAt)}` : '');
  }
}

// ── Init ──────────────────────────────────────────────────────────────────────

let newsLoaded = false;

async function initNews() {
  if (newsLoaded) return;

  document.getElementById('news-nikkei').innerHTML =
    '<p class="news-loading">Loading...</p>';

  try {
    const res = await fetch('news.json?_=' + Date.now());
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json();
    renderNews(data);
    newsLoaded = true;
  } catch (e) {
    document.getElementById('news-nikkei').innerHTML =
      `<p class="news-error">Could not load news.json — run the GitHub Action first.<br><small>${e}</small></p>`;
  }
}

// Load immediately on page open (script runs after DOM is parsed)
initNews();
