// ── News ──────────────────────────────────────────────────────────────────────
// Reads news.json generated by GitHub Actions (fetch_news.py + Gemini API).

function timeAgo(isoString) {
  const diff = Date.now() - new Date(isoString).getTime();
  const m = Math.floor(diff / 60000);
  if (m < 1)  return 'just now';
  if (m < 60) return `${m}m ago`;
  const h = Math.floor(m / 60);
  if (h < 24) return `${h}h ago`;
  return `${Math.floor(h / 24)}d ago`;
}

// ── Morning paper link ────────────────────────────────────────────────────────

function morningPaperUrl() {
  const jst = new Date(Date.now() + 9 * 60 * 60 * 1000);
  if (jst.getUTCHours() < 4) jst.setUTCDate(jst.getUTCDate() - 1);
  const y = jst.getUTCFullYear();
  const m = String(jst.getUTCMonth() + 1).padStart(2, '0');
  const d = String(jst.getUTCDate()).padStart(2, '0');
  return `https://www.nikkei.com/paper-viewer?TYPE=VIEWERBYPAGE&editionID=${y}${m}${d}M101`;
}

function renderMorningPaperLink() {
  document.getElementById('nikkei-paper-link').href = morningPaperUrl();
}

// ── Render ────────────────────────────────────────────────────────────────────

function renderNewsCard(a) {
  const img = a.image
    ? `<img class="news-card-img" src="${a.image}" alt="" loading="lazy" onerror="this.parentElement.remove()">`
    : '';
  return `
    <a class="news-card" href="${a.url}" target="_blank" rel="noopener noreferrer">
      ${img ? `<div class="news-card-thumb">${img}</div>` : ''}
      <div class="news-card-body">
        <span class="news-title">${a.summary}</span>
        <span class="news-detail">${a.title}</span>
        <span class="news-time">${a.pub ? timeAgo(a.pub) : ''}</span>
      </div>
    </a>
  `;
}

function renderNews(data) {
  const grid = document.getElementById('news-grid');

  if (!data.columns || !data.columns.length) {
    grid.innerHTML = '<p class="news-error">No articles.</p>';
    return;
  }

  grid.innerHTML = data.columns.map(col => `
    <div class="news-col">
      <h3 class="news-col-title">${col.title}</h3>
      <div class="news-list">
        ${col.articles.length
          ? col.articles.map(renderNewsCard).join('')
          : '<p class="news-error">No articles.</p>'}
      </div>
    </div>
  `).join('');

  if (data.fetchedAt) {
    document.getElementById('news-meta').textContent =
      `Updated ${timeAgo(data.fetchedAt)}`;
  }
}

// ── Init ──────────────────────────────────────────────────────────────────────

let newsLoaded = false;

async function initNews() {
  if (newsLoaded) return;

  renderMorningPaperLink();
  document.getElementById('news-grid').innerHTML =
    '<p class="news-loading">Loading...</p>';

  try {
    const res = await fetch('news.json?_=' + Date.now());
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json();
    renderNews(data);
    newsLoaded = true;
  } catch (e) {
    document.getElementById('news-grid').innerHTML =
      `<p class="news-error">Could not load news.json.<br><small>${e}</small></p>`;
  }
}

// Load immediately on page open
initNews();
